version: '3.9'

services:
  podcast-api:
    image: "eclipse-temurin:21.0.1_12-jre-alpine"
    ports:
      - "80:8080"
    volumes:
      - "./build/libs/podcast-api.jar:/podcast-api.jar"
    command: "java -jar podcast-api.jar"
    restart: always
    deploy:
      resources:
        limits:
          memory: 600M
    networks:
      - podcast-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PODCAST_API_DB_URI=${PODCAST_API_DB_URI}
      - PODCAST_API_DB_USERNAME=${PODCAST_API_DB_USERNAME}
      - PODCAST_API_DB_PASSWORD=${PODCAST_API_DB_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GENERIC_USER_USERNAME=${GENERIC_USER_USERNAME}
      - GENERIC_USER_PASSWORD=${GENERIC_USER_PASSWORD}

networks:
  podcast-api:
    name: podcast-api
    driver: bridge