version: '3.9'

services:
  podcast-api:
    image: "openjdk:16.0-jdk-slim"
    ports:
      - "9001:8080"
    volumes:
      - "./build/libs/podcast-api.jar:/podcast-api.jar"
    command: "java -jar podcast-api.jar"
    restart: always
    deploy:
      resources:
        limits:
          memory: 600M
    networks:
      - podcast-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PODCAST_API_DB_URI=${PODCAST_API_DB_URI}
      - PODCAST_API_DB_USERNAME=${PODCAST_API_DB_USERNAME}
      - PODCAST_API_DB_PASSWORD=${PODCAST_API_DB_PASSWORD}

networks:
  podcast-api:
    name: podcast-api
    driver: bridge