version: '3.8'

services:
  podcast-api:
    image: "openjdk:17.0-jdk-slim"
    ports:
      - "9001-9003:8080"
    volumes:
      - "./build/libs/Podcast-API-1.0.2.jar:/podcast-api.jar"
    command: "java -jar podcast-api.jar"
    restart: always
    networks:
      - podcast-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  podcast-api:
    name: podcast-api
    driver: bridge