server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://${PODCAST_API_DB_URI}"
    username: "${PODCAST_API_DB_USERNAME}"
    password: "${PODCAST_API_DB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update